### ISSUE TITLE
Improve robustness of PD algorithm

### ISSUE THREAD

**Issue by physikerwelt** [TU-Berlin/mathosphere#118]
I was doing a test run with the simple pd algorithm on the server
```
ubuntu@master:/data/mathosphere/mathosphere-core/target$ /srv/flink/bin/flink run mathosphere-core-3.0.0-SNAPSHOT-jar-with-dependencies.jar pd --inputDir hdfs://m:54310/data/ntcir/12/arxiv/xhtml/together.xml --outputDir hdfs://m:54310/out/m1 --referenceDir hdfs://m:54310/data/ex1.html
```
and got the following exception
```
Caused by: java.lang.Exception: Serialized representation of javax.xml.xpath.XPathExpressionException: net.sf.saxon.trans.XPathException: Finding root of tree: the context item is absent
        at net.sf.saxon.xpath.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:378)
        at com.formulasearchengine.mathmlquerygenerator.xmlhelper.XMLHelper.getElementsB(XMLHelper.java:184)
        at com.formulasearchengine.mathosphere.mathpd.pojos.ArxivDocument.getMathTags(ArxivDocument.java:33)
        at com.formulasearchengine.mathosphere.mathpd.pojos.ArxivDocument.getCElements(ArxivDocument.java:38)
        at com.formulasearchengine.mathosphere.mathpd.FlinkPd$1.reduce(FlinkPd.java:41)
        at org.apache.flink.runtime.operators.AllGroupReduceDriver.run(AllGroupReduceDriver.java:148)
        at org.apache.flink.runtime.operators.BatchTask.run(BatchTask.java:486)
        at org.apache.flink.runtime.operators.BatchTask.invoke(BatchTask.java:351)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:584)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by fhamborg** [comment]
I need some more context on this, e.g., do you think that I caused this
issue or why do you assign this to me?

**Comment by physikerwelt** [comment]
Let's discuss the details on Monday in the office. I discussed with @nmeuschke how to share the workload more efficient.

**Comment by fhamborg** [comment]
fixed locally, lets discuss
